version: '3'

services:
  app:
    build:
      context: .
      dockerfile: development.Dockerfile
    environment:
      - VIRTUAL_HOST=app-local.ja
      - DB_URL=mongodb://mongodb/wtmbjs-project
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - mongodb
  
  mongodb:
    image: mongo:latest

  load-balancer:
    image: dockercloud/haproxy
    links:
      - app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8000:80
      - 443:4430
    restart: on-failure